version: '3.9'

services:
  dev-container:
    image: ubuntu:latest
    container_name: dev-container
    tty: true
    stdin_open: true
    volumes:
      - ./dev:/workspace
    working_dir: /workspace
    command: /bin/bash

  jenkins-server:
    image: jenkins/jenkins:lts
    container_name: jenkins-server
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    restart: unless-stopped

  jenkins-agent:
    image: jenkins/agent:latest
    container_name: jenkins-agent
    environment:
      - JENKINS_URL=http://jenkins-server:8080
      - JENKINS_AGENT_NAME=agent
      - JENKINS_SECRET=
      - JENKINS_AGENT_WORKDIR=/home/jenkins/agent
    depends_on:
      - jenkins-server
    volumes:
      - /home/jenkins:/home/jenkins
    restart: unless-stopped

volumes:
  jenkins_home:
